import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import AppShell from "../Layout/AppShell";
import CubeScene from "../Three/CubeScene";
import { Panel, PageHeader, Button, Note } from "../Components/ui.jsx";
import { parseCubeString } from "../lib/cubeInput.js";
import { facesToFacelets, faceletsToFaces } from "../cube/facelets.js";
import { COLOUR_HEX } from "../cube/notation.js";
import { cubeApi, ApiError } from "../lib/api.js";
import { useCubeStore } from "../store/cubeStore.js";

const PALETTE = [
  ["W", "white"],
  ["Y", "yellow"],
  ["R", "red"],
  ["O", "orange"],
  ["G", "green"],
  ["B", "blue"],
];

const FACE_LABELS = { U: "Top", R: "Right", F: "Front", D: "Bottom", L: "Left", B: "Back" };

export default function CubeInput() {
  const navigate = useNavigate();
  const loadScramble = useCubeStore((s) => s.loadScramble);

  const [inputStr, setInputStr] = useState("");
  const [localError, setLocalError] = useState("");
  const [facelets, setFacelets] = useState(null);
  const [server, setServer] = useState(null);
  const [busy, setBusy] = useState(false);
  const [apiError, setApiError] = useState("");

  /** Parse locally on every keystroke -- instant feedback, no network. */
  const handleInputChange = (e) => {
    const val = e.target.value;
    setInputStr(val);
    setServer(null);
    setApiError("");

    if (!val.trim()) {
      setLocalError("");
      setFacelets(null);
      return;
    }
    try {
      const faces = parseCubeString(val);
      const fl = facesToFacelets(faces);
      setFacelets(fl);
      setLocalError("");
      loadScramble(fl);
    } catch (err) {
      setLocalError(err.message);
      setFacelets(null);
    }
  };

  /**
   * Second opinion from the backend. Local checks catch colour counts and
   * impossible centres; only the solver can catch a PARITY violation -- a cube
   * with perfect colour counts that still cannot physically be assembled.
   */
  useEffect(() => {
    if (!facelets) return;
    let cancelled = false;
    cubeApi
      .validate(facelets)
      .then((res) => {
        if (!cancelled) setServer(res);
      })
      .catch((err) => {
        if (!cancelled) setApiError(err.message);
      });
    return () => {
      cancelled = true;
    };
  }, [facelets]);

  const checking = Boolean(facelets) && server === null && !apiError;

  /** FR-16 -- a guaranteed-solvable scramble, generated by the backend. */
  const handleScramble = async () => {
    setBusy(true);
    setApiError("");
    try {
      const { facelets: fl } = await cubeApi.scramble(20);
      setInputStr(fl.toUpperCase());
      setFacelets(fl);
      setLocalError("");
      loadScramble(fl);
    } catch (err) {
      setApiError(
        err instanceof ApiError && err.status === 0
          ? "Backend offline — start it on port 8000 and try again."
          : err.message,
      );
    } finally {
      setBusy(false);
    }
  };

  const handleSolveClick = async () => {
    if (!facelets) return;
    setBusy(true);
    setApiError("");
    try {
      // Fetch the optimal solution up front: its length is the denominator of
      // the efficiency score, needed even in Interactive mode.
      const optimal = await cubeApi.solve(facelets, "optimal");
      loadScramble(facelets, optimal.optimalMoveCount);
      navigate("/solve");
    } catch (err) {
      setApiError(err.message);
    } finally {
      setBusy(false);
    }
  };

  const ready = Boolean(facelets) && server?.valid !== false;

  return (
    <AppShell>
      <PageHeader
        title="Cube Input"
        subtitle="Paste a cube state, generate a random one, or scan it with your camera"
      >
        <Button onClick={handleScramble} disabled={busy}>
          {busy ? "..." : "Random scramble"}
        </Button>
        <Button onClick={() => navigate("/scan")}>Use camera</Button>
      </PageHeader>

      <div className="grid gap-4 lg:grid-cols-[1fr_20rem] items-start">
        <div className="min-w-0 space-y-4">
          <Panel
            title="Cube state"
            action={
              <span className="text-[11px] font-mono text-gray-500">
                {inputStr.replace(/\s/g, "").length}/54
              </span>
            }
          >
            <textarea
              className="w-full h-64 rounded-xl p-4 bg-dark-bg border border-dark-border font-mono text-sm text-white resize-none outline-none transition-colors focus:border-neon-blue focus:ring-1 focus:ring-neon-blue placeholder:text-gray-600"
              value={inputStr}
              onChange={handleInputChange}
              spellCheck={false}
              placeholder={
                "Paste 54 characters in U R F D L B order, or 6 lines of 9.\n" +
                "Colours: W Y R O B G\n\n" +
                "Or press Random scramble to pull one from the backend."
              }
            />

            <div className="flex flex-wrap items-center gap-3 mt-3">
              <span className="text-[11px] text-gray-500">Colour letters</span>
              {PALETTE.map(([letter, name]) => (
                <span
                  key={letter}
                  className="flex items-center gap-1.5 text-[11px] text-gray-400"
                  title={name}
                >
                  <span
                    className="w-3.5 h-3.5 rounded border border-white/15"
                    style={{ background: COLOUR_HEX[letter.toLowerCase()] }}
                  />
                  {letter}
                </span>
              ))}
            </div>
          </Panel>

          <Panel title="Face order">
            <div className="flex flex-wrap gap-2">
              {Object.entries(FACE_LABELS).map(([f, label], i) => (
                <span
                  key={f}
                  className="px-2.5 py-1.5 rounded-lg border border-dark-border bg-dark-bg/60 text-[11px] text-gray-400"
                >
                  <span className="font-mono text-neon-blue">{f}</span> {label}
                  <span className="text-gray-600 ml-1.5">
                    chars {i * 9 + 1}–{i * 9 + 9}
                  </span>
                </span>
              ))}
            </div>
          </Panel>
        </div>

        <div className="space-y-4">
          <Panel
            title="Status"
            tone={
              localError || server?.valid === false
                ? "rose"
                : server?.valid
                  ? "green"
                  : "default"
            }
          >
            {localError ? (
              <Note tone="error">{localError}</Note>
            ) : checking ? (
              <p className="text-xs text-gray-400 pbs-pulse">
                Checking with the solver...
              </p>
            ) : server?.valid === false ? (
              <Note tone="error">Backend rejected it: {server.detail}</Note>
            ) : server?.valid ? (
              <Note tone="success">
                Valid and solvable — confirmed by the solver.
              </Note>
            ) : facelets ? (
              <Note tone="info">Format looks right.</Note>
            ) : (
              <p className="text-xs text-gray-500">Waiting for input...</p>
            )}

            {apiError && (
              <Note tone="error" className="mt-3">
                {apiError}
              </Note>
            )}

            <Button
              variant="primary"
              size="md"
              className="w-full mt-3"
              onClick={handleSolveClick}
              disabled={!ready || busy}
            >
              {busy ? "Contacting solver..." : "Solve this cube"}
            </Button>
          </Panel>

          <Panel title="Preview">
            <div className="h-52 rounded-xl overflow-hidden bg-dark-bg border border-dark-border grid place-items-center">
              {facelets ? (
                <CubeScene />
              ) : (
                <span className="text-xs text-gray-600">Nothing to show yet</span>
              )}
            </div>
            {facelets && (
              <div className="mt-3 grid grid-cols-3 gap-2">
                {Object.entries(faceletsToFaces(facelets)).map(([f, arr]) => (
                  <div key={f} className="flex items-center gap-1.5 text-[11px] text-gray-400">
                    <span
                      className="w-3 h-3 rounded border border-white/15"
                      style={{ background: COLOUR_HEX[arr[4].toLowerCase()] }}
                    />
                    {FACE_LABELS[f]}
                  </div>
                ))}
              </div>
            )}
          </Panel>

          <Panel title="Algorithm">
            <p className="text-xs text-gray-300">Kociemba two-phase (optimal)</p>
            <p className="text-[11px] text-gray-500 mt-1">
              Beginner&apos;s method powers Guided Mode.
            </p>
          </Panel>
        </div>
      </div>
    </AppShell>
  );
}
