import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import AppShell from "../Layout/AppShell";
import CubeScene from "../Three/CubeScene";
import NetEditor from "../Components/NetEditor";
import CameraScan from "../Components/CameraScan";
import { parseCubeString } from "../lib/cubeInput.js";
import { facesToFacelets, faceletsToFaces } from "../cube/facelets.js";
import { cubeApi, ApiError } from "../lib/api.js";
import { useCubeStore } from "../store/cubeStore.js";

function Card({ title, right, children }) {
  return (
    <div className="bg-dark-surface border border-dark-border hover:border-white/10 transition-colors rounded-xl p-4">
      <div className="flex items-center justify-between mb-3">
        <div className="text-xs font-semibold uppercase tracking-wider text-gray-400">
          {title}
        </div>
        {right}
      </div>
      {children}
    </div>
  );
}

const PALETTE = {
  W: "#ffffff",
  Y: "#ffd400",
  R: "#ff4d4d",
  O: "#ff8c00",
  B: "#2d4cff",
  G: "#2ecc71",
};

export default function CubeInput() {
  const navigate = useNavigate();
  const loadScramble = useCubeStore((s) => s.loadScramble);

  const [inputStr, setInputStr] = useState("");
  const [localError, setLocalError] = useState("");
  const [facelets, setFacelets] = useState(null); // locally valid, 54 lowercase
  const [server, setServer] = useState(null); // { valid, detail } from backend
  const [busy, setBusy] = useState(false);
  const [apiError, setApiError] = useState("");

  // --- input mode: "text" | "manual" | "camera" ---
  const [inputMode, setInputMode] = useState("text");
  const [netKey, setNetKey] = useState(0);
  const [netInitial, setNetInitial] = useState(null);
  const [scanNotice, setScanNotice] = useState("");

  /** Parse locally on every keystroke -- instant feedback, no network. */
  const handleInputChange = (e) => {
    const val = e.target.value;
    setInputStr(val);
    setServer(null);
    setApiError("");
    setScanNotice("");

    if (!val.trim()) {
      setLocalError("");
      setFacelets(null);
      return;
    }
    try {
      const faces = parseCubeString(val);
      const fl = facesToFacelets(faces);
      setFacelets(fl);
      setLocalError("");
      loadScramble(fl); // preview follows the input
    } catch (err) {
      setLocalError(err.message);
      setFacelets(null);
    }
  };

  /** Handle facelets coming from the manual net editor. */
  const handleNetChange = useCallback(
    (fl) => {
      setServer(null);
      setApiError("");
      if (fl) {
        setFacelets(fl);
        setInputStr(fl.toUpperCase()); // keep text in sync for tab switch
        setLocalError("");
        loadScramble(fl);
      } else {
        setFacelets(null);
      }
    },
    [loadScramble],
  );

  /** Switch to manual mode, pre-filling net from current facelets. */
  const switchToManual = () => {
    setInputMode("manual");
    setLocalError("");
    if (facelets) {
      setNetInitial(facelets);
      setNetKey((k) => k + 1);
    }
  };

  /** Switch to text mode, syncing the textarea from current facelets. */
  const switchToText = () => {
    setInputMode("text");
    if (facelets) {
      setInputStr(facelets.toUpperCase());
    }
  };

  /** Switch to camera scan mode. */
  const switchToCamera = () => {
    setInputMode("camera");
    setLocalError("");
  };

  /** Handle successful OpenCV camera scan result */
  const handleScanComplete = (scannedFacelets, scanMeta) => {
    setFacelets(scannedFacelets);
    setInputStr(scannedFacelets.toUpperCase());
    setNetInitial(scannedFacelets);
    setNetKey((k) => k + 1);
    loadScramble(scannedFacelets);

    if (scanMeta?.valid) {
      setScanNotice("✓ Camera scan successful! Review stickers below and click 'Solve Cube'.");
    } else {
      setScanNotice(
        `⚠️ Scan extracted 54 stickers with validation note: ${scanMeta?.detail || "Please verify colors on the 2D Net below."}`
      );
    }

    // Automatically transition to Manual Net editor for user confirmation (FR-06c)
    setInputMode("manual");
  };

  /**
   * Second opinion from the backend. Local checks catch colour counts and
   * impossible centres; only the solver can catch a PARITY violation -- a cube
   * with perfect colour counts that still cannot be assembled.
   */
  useEffect(() => {
    if (!facelets) return;
    let cancelled = false;

    cubeApi
      .validate(facelets)
      .then((res) => {
        if (!cancelled) setServer(res);
      })
      .catch((err) => {
        if (!cancelled) setApiError(err.message);
      });

    return () => {
      cancelled = true;
    };
  }, [facelets]);

  // Derived, not stored: we are waiting on the solver whenever the string
  // parses locally but the backend has not answered for it yet.
  const checking = Boolean(facelets) && server === null && !apiError;

  /** FR-16 -- a guaranteed-solvable scramble, generated by the backend. */
  const handleScramble = async () => {
    setBusy(true);
    setApiError("");
    setScanNotice("");
    try {
      const { facelets: fl } = await cubeApi.scramble(20);
      setInputStr(fl.toUpperCase());
      setFacelets(fl);
      setLocalError("");
      loadScramble(fl);
      // Pre-fill the net editor so switching to manual shows the scramble
      setNetInitial(fl);
      setNetKey((k) => k + 1);
    } catch (err) {
      setApiError(
        err instanceof ApiError && err.status === 0
          ? "Backend offline -- start it on port 8000 and try again."
          : err.message,
      );
    } finally {
      setBusy(false);
    }
  };

  const handleSolveClick = async () => {
    if (!facelets) return;
    setBusy(true);
    setApiError("");
    try {
      // Fetch the optimal solution up front: its length is the denominator of
      // the efficiency score, needed even in Interactive mode.
      const optimal = await cubeApi.solve(facelets, "optimal");
      loadScramble(facelets, optimal.optimalMoveCount);
      navigate("/solve");
    } catch (err) {
      setApiError(err.message);
    } finally {
      setBusy(false);
    }
  };

  const ready = Boolean(facelets) && server?.valid !== false;

  let statusText = "Waiting for input...";
  let statusTone = "text-gray-400";
  if (localError) {
    statusText = localError;
    statusTone = "text-red-400";
  } else if (checking) {
    statusText = "Checking with solver...";
    statusTone = "text-gray-400";
  } else if (server?.valid === false) {
    statusText = `Backend rejected: ${server.detail}`;
    statusTone = "text-red-400";
  } else if (server?.valid) {
    statusText = "Valid and solvable (verified by backend)";
    statusTone = "text-neon-green";
  } else if (facelets) {
    statusText = "Format OK";
    statusTone = "text-neon-green";
  } else if (inputMode === "manual") {
    statusText = "Paint all stickers to continue";
  } else if (inputMode === "camera") {
    statusText = "Capturing cube faces with camera...";
  }

  return (
    <AppShell>
      <div className="flex gap-4 h-[calc(100vh-2rem)]">
        <div className="flex-1 flex flex-col gap-4 min-w-0">
          {/* ── header ──────────────────────────────────────────── */}
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-bold tracking-tight text-white">
              Cube Input
            </h2>
            <div className="flex gap-2">
              <button
                onClick={handleScramble}
                disabled={busy}
                className="px-3 py-1.5 rounded-lg border border-neon-green/60 bg-neon-green/10 text-neon-green text-xs font-medium cursor-pointer transition-colors hover:bg-neon-green/20 disabled:opacity-40"
              >
                {busy ? "..." : "Random Scramble"}
              </button>
              <div className="flex rounded-lg border border-dark-border overflow-hidden">
                <button
                  onClick={switchToCamera}
                  className={`px-3 py-1.5 text-xs font-medium cursor-pointer transition-colors flex items-center gap-1.5 ${
                    inputMode === "camera"
                      ? "bg-neon-blue/15 text-neon-blue"
                      : "text-gray-400 hover:text-white hover:bg-white/5"
                  }`}
                >
                  <span>📷</span> Camera Scan
                </button>
                <button
                  onClick={switchToManual}
                  className={`px-3 py-1.5 text-xs font-medium cursor-pointer transition-colors border-l border-dark-border ${
                    inputMode === "manual"
                      ? "bg-neon-blue/15 text-neon-blue"
                      : "text-gray-400 hover:text-white hover:bg-white/5"
                  }`}
                >
                  Manual Net
                </button>
                <button
                  onClick={switchToText}
                  className={`px-3 py-1.5 text-xs font-medium cursor-pointer transition-colors border-l border-dark-border ${
                    inputMode === "text"
                      ? "bg-neon-blue/15 text-neon-blue"
                      : "text-gray-400 hover:text-white hover:bg-white/5"
                  }`}
                >
                  Text
                </button>
              </div>
            </div>
          </div>

          {/* ── scan notice if available ── */}
          {scanNotice && (
            <div className="text-xs p-3 rounded-xl border border-neon-blue/40 bg-neon-blue/10 text-neon-blue flex items-center justify-between">
              <span>{scanNotice}</span>
              <button
                type="button"
                onClick={() => setScanNotice("")}
                className="text-gray-400 hover:text-white ml-2 text-sm"
              >
                ✕
              </button>
            </div>
          )}

          {/* ── input workspace ──────────────────────────────────── */}
          <Card
            title={
              inputMode === "camera"
                ? "Camera capture (OpenCV)"
                : inputMode === "manual"
                ? "Interactive 2D net editor"
                : "Text input workspace"
            }
            right={
              inputMode === "text" ? (
                <span
                  className={`text-[11px] font-mono ${
                    inputStr.replace(/\s/g, "").length === 54
                      ? "text-neon-green"
                      : inputStr.replace(/\s/g, "").length >= 40
                        ? "text-yellow-400"
                        : "text-gray-500"
                  }`}
                >
                  {inputStr.replace(/\s/g, "").length}/54
                </span>
              ) : null
            }
          >
            {inputMode === "camera" ? (
              /* ── camera scan mode (FR-04, FR-06a) ─────────────── */
              <CameraScan
                onScanComplete={handleScanComplete}
                onCancel={switchToManual}
              />
            ) : inputMode === "manual" ? (
              /* ── manual net mode (FR-05, FR-06c) ──────────────── */
              <NetEditor
                key={netKey}
                initialFacelets={netInitial}
                onChange={handleNetChange}
              />
            ) : (
              /* ── text mode ────────────────────────────────────── */
              <>
                <textarea
                  className="w-full h-[380px] rounded-xl p-4 bg-dark-bg text-white border border-dark-border font-mono text-sm resize-none focus:outline-none focus:border-neon-blue/50 focus:shadow-[0_0_15px_rgba(0,243,255,0.15)] transition-colors placeholder:text-gray-600"
                  value={inputStr}
                  onChange={handleInputChange}
                  spellCheck={false}
                  placeholder={
                    "Paste 54 characters (URFDLB order), or 6 lines of 9.\n" +
                    "Colours: W Y R O B G\n\n" +
                    "Or hit Random Scramble to pull one from the backend."
                  }
                />

                <div className="flex items-center justify-between mt-3 text-xs">
                  <div className="flex items-center gap-2">
                    <span className="text-gray-400">Colours</span>
                    {Object.entries(PALETTE).map(([letter, c]) => (
                      <span
                        key={letter}
                        title={letter}
                        className="w-5 h-5 rounded border border-white/10 inline-block hover:scale-125 transition-transform cursor-help"
                        style={{ background: c }}
                      />
                    ))}
                  </div>
                  <span className="text-gray-500">
                    Face order: U R F D L B
                  </span>
                </div>
              </>
            )}
          </Card>
        </div>

        {/* ── sidebar ───────────────────────────────────────────── */}
        <div className="w-80 flex flex-col gap-4 shrink-0">
          <Card title="Status">
            <div
              className={`text-xs font-medium mb-3 transition-all duration-300 ${statusTone}`}
            >
              {statusText}
            </div>

            {apiError && (
              <div className="text-xs text-red-400 mb-3 border border-red-500/30 bg-red-500/5 rounded-lg p-2">
                {apiError}
              </div>
            )}

            <button
              className={`w-full py-3 px-4 rounded-xl font-bold text-sm transition-all ${
                ready && !busy
                  ? "bg-neon-blue text-dark-bg hover:opacity-90 cursor-pointer shadow-[0_0_20px_rgba(0,243,255,0.3)] hover:shadow-[0_0_30px_rgba(0,243,255,0.4)]"
                  : "bg-gray-800 text-gray-500 border border-dark-border cursor-not-allowed"
              }`}
              onClick={handleSolveClick}
              disabled={!ready || busy}
            >
              {busy ? "Contacting solver..." : "Solve Cube"}
            </button>
          </Card>

          <Card title="Algorithm">
            <div className="text-xs text-gray-300 font-medium">
              Kociemba 2-phase (optimal)
            </div>
            <div className="text-xs text-gray-500 mt-1">
              Beginner&apos;s method for guided mode
            </div>
          </Card>

          <Card title="Preview">
            <div className="h-56 rounded-xl overflow-hidden bg-black border border-dark-border flex items-center justify-center">
              {facelets ? (
                <CubeScene />
              ) : (
                <span className="text-xs text-gray-600">
                  Invalid / empty state
                </span>
              )}
            </div>
            {facelets && (
              <div className="mt-2 text-[10px] text-gray-500 font-mono break-all">
                {Object.entries(faceletsToFaces(facelets))
                  .map(([f, arr]) => `${f}:${arr[4]}`)
                  .join("  ")}
              </div>
            )}
          </Card>
        </div>
      </div>
    </AppShell>
  );
}
